//!!!!!! DO NOT EDIT THIS FILE MANUALLY IT IS GENERATED DURING A BUILD!!!!!!!!
var IntentaVars = {
    "version": "2.0.0",
    "templates_version": "2015-07-21",
    "local": {
        "domain": "pixel.local.intenta.io"
    },
    "development": {
        "domain": "pixel.dev.intenta.io"
    },
    "sandbox": {
        "domain": "pixel.sandbox.intenta.io"
    },
    "production": {
        "domain": "pixel.intenta.io"
    },
    "global": {
        "name": "Intenta-Chrome-SDK"
    }
};