//!!!!!! DO NOT EDIT THIS FILE MANUALLY IT IS GENERATED DURING A BUILD!!!!!!!!
var IntentaVars = {
    "version": "2.0.1",
    "templates_version": "20150721",
    "local": {
        "domain": "pixel.local.intenta.io",
        "debug": true
    },
    "development": {
        "domain": "pixel.dev.intenta.io",
        "debug": true
    },
    "production": {
        "domain": "pixel.intenta.io",
        "debug": false
    },
    "global": {
        "name": "Intenta-Chrome-SDK"
    }
};